### ISSUE TITLE
Too many columns specified: expected 5 and found 1

### ISSUE THREAD

**Issue by KEJdev** [MatheusNali/rulbearingpredictor#3]
Thank you very much for providing us with a great code.
But, by the way, I've got a problem.  

read_data function is not fleshed out.  
Can you help me?

**Comment by MatheusNali** [comment]
Hello! Thank you for your comments.

Are you using FEMTO dataset? 

If yes, there are some differences about the separator in the .csv files (Some of them are separated by ; and others by ,). You can check this looking the .csv files in some text editor (like vim or visual studio code...). 

Because of that, if you read some .csv file separated by ; using , as separator, pd.read_csv will not separate the columns resulting the problem.

I solved this problem in this way:
1. Check if is a , or ; csv file.
2. Use sep parameter in pandas read_csv to specify the separator (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). 

*To check for ,  or  ;  you can just read a file and check its length (separator is just a variable that you can pass to the sep parameter):
if len(pd.read_csv(path_to_csv_file).values[0]) == 1:
                separator = ';'

**After reading the data to memory you can use pd.concat to concatenate all csv files of a bearing in-to one dataframe and then write to a csv file using .to_csv. In this way it will be faster to read and you won't have those problems with separators (by default pandas use , separator).

If you have any questions, feel free to ask!
Good luck!

**Comment by KEJdev** [comment]
I'm sorry to ask.   T^T

I'm from 297 in machine_learning_tools.py row error.
So, except the rus, 301 to run from the second row.

By the way, hht cnn _ shape itself is not right.
Debugging of config.py to the shape and shape it's different.

 By any chance, can you give me advice?
A good code sharing, but I am sorry to bother you again and again.  T^T

2019년 10월 25일 (금) 오후 1:26, Matheus Nali <notifications@github.com>님이 작성:

**Comment by MatheusNali** [comment]
Hello,

Don't worry about the questions. I didn't understand your problem, could you talk with me by email (matheus.nali@usp.br) and show the errors? 

By the way, this project is not complete.  I didn't finish the remaining useful life estimation part (LSTM regression) due to some problems with the paper and theory knowledge.  I just finished data processing algorithms and health assessment classification (CNN).

I've stared a new one (https://github.com/MatheusNali/Bearing-RUL-Predict) which I will update with some algorithms soon.
